name: polygon_finder
description: Library to help you to find the polygons from defined set of lines
version: 1.0.1
repository: https://github.com/xommmax/polygon_finder

environment:
  sdk: ^3.0.5

dependencies:
  collection: ^1.18.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
